name: Testing

on:
  push:
    branches:
        - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.12']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements_dev.txt
        python -m pip install tox tox-gh-actions
    - name: Install in dev mode
      run:  python -m pip install -e . -vv
    - name: Lint with pylint
      run: pylint teensytoany
    - name: isort
      run: isort --check-only .
    - name: Test with tox
      run: tox
